### ISSUE TITLE
绕过Mtb鉴权失效


### ISSUE THREAD

**Issue by Hua159** [Xposed-Modules-Repo/com.weverses.modempro#1]
红米k60p
鲁班mtb5.2
基带版本3.0
开启之后重启，然后输入代码进入鲁班闪退，未插卡(?这个的原因)
![Screenshot_2023-09-11-17-25-24-631_com.tencent.mobileqq.jpg](https://github.com/Xposed-Modules-Repo/com.weverses.modempro/assets/103234291/06de9cf1-e0e1-4834-a2ff-3dd6e2313fa1)

**Comment by Weverses** [comment]
2.2.0版本应该已经修复了，你可以试试
